spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tms
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

